'use server';

/**
 * @fileOverview An AI-powered tool to generate an itemized quote for game development costs.
 *
 * - generateQuote - A function that handles the cost calculation process.
 * - QuoteGeneratorInput - The input type for the generateQuote function.
 * - QuoteGeneratorOutput - The return type for the generateQuote function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const QuoteGeneratorInputSchema = z.object({
  gameIdea: z
    .string()
    .describe('A detailed description of the game idea, which can be a simple concept or a full Game Design Document (GDD).'),
});
export type QuoteGeneratorInput = z.infer<typeof QuoteGeneratorInputSchema>;

const QuoteItemSchema = z.object({
    name: z.string().describe("The name of the feature or module."),
    description: z.string().describe("A brief description of what this module includes."),
    cost: z.number().describe("The estimated cost for this specific module in USD."),
});
export type QuoteItem = z.infer<typeof QuoteItemSchema>;


const QuoteGeneratorOutputSchema = z.object({
    quoteTitle: z.string().describe("A descriptive title for the quote, e.g., 'Project Development Quote'."),
    items: z.array(QuoteItemSchema).describe("An array of all the features/modules with their descriptions and costs."),
    totalCost: z.number().describe("The sum of all module costs."),
    disclaimer: z.string().describe("A concluding note or disclaimer for the user."),
});
export type QuoteGeneratorOutput = z.infer<typeof QuoteGeneratorOutputSchema>;

export async function generateQuote(input: QuoteGeneratorInput): Promise<QuoteGeneratorOutput> {
  return quoteGeneratorFlow(input);
}

const prompt = ai.definePrompt({
  name: 'quoteGeneratorPrompt',
  input: {schema: QuoteGeneratorInputSchema},
  output: {schema: QuoteGeneratorOutputSchema},
  prompt: `You are an expert game development project manager working for "Shahrukh Yousafzai". Your task is to analyze a client's game idea/GDD and generate a detailed, itemized quote for the development cost.

Break down the project into logical modules/features. For each module, provide a name, a short description of the work involved, and an estimated cost in USD. The costs should be realistic and based on the complexity described.

Use the provided project history and quote examples to inform your cost breakdown and structure. The sum of all module costs should equal the total cost.

**IMPORTANT RULES:**
1.  Always break the project down into multiple, specific modules. Do not provide a single lump-sum cost.
2.  The FIRST item in the quote MUST be a "Prototype" module. This prototype should cover the core gameplay loop and basic mechanics. Its cost should be between $500 and $1500, depending on the project's complexity.
3.  The final output must include a "disclaimer" field with the following text: "This is an estimated quote generated by AI. For a final, official quote, please contact Shahrukh Yousafzai with this document."

**Project History & Pricing Context (for your reference):**
- NFT/P2E/Web3 Game (Mobile/Web/PC): $2,500
- 2D/3D Game (Mobile/Desktop/Web): $350
- High Quality AAA Game (PC/Mobile): $750 - $1,250
- MMORPG Project: $8,000
- 3D Monster Hunt/Kingdom Defense Prototype: $18,400 (Full project scope)
- AI Chatbot with Voice/3D Avatar: $2,000
- Game UI/Art: $800
- Multiplayer functionality is usually an add-on costing between $500 - $2000.
- A full login system (auth, registration, password reset) is around $500.
- A database for player data is around $700.

**Quote Example 1:**
- Game Idea: MMORPG with warrior class, 2 enemy types, chat, login.
- Quote Breakdown:
    1. Prototype (Core combat & movement) - $700
    2. Character Selection System – $500
    3. Two NPCs with Combat AI – $600
    4. Global Chat System – $300
    5. Player Data Database – $700
    6. In-Game Coins/Currency System – $300
    7. Full Login System (with Account Creation & Password Reset) – $500
    8. Two Additional Abilities for Warrior Character – $600
- Total Quote: $3,500

**Quote Example 2:**
- Game Idea: Full Game - Doruzu Land (Android) with pets, farming, building, multiplayer, Web3.
- Quote Breakdown:
    1. Prototype (Core Movement, Interaction, Basic UI) - $1,500
    2. Character Customizer - $1,800
    3. RugDollz Pet System - $900
    4. NFT Land Ownership - $1,200
    5. Farming & Crafting System - $1,000
    6. Survival-Lite (Building/Tree Cutting) - $1,000
    7. Ruglings NPCs (Quest Givers) - $800
    8. Trollz NPCs (Shopkeepers) - $700
    9. 2 Environments (Japanese City + Countryside) - $1,700
    10. Multiplayer: Visit Friends - $900
    11. Web3 Wallet Integration (ApeChain) - $700
    12. Database & Backend & In-Game Purchases - $800
    13. Professional UI Design - $800
    14. Daily Login Rewards + NFT Profile Pic - $600
    15. Add Friends Feature - $600
- Total Quote: $14,400 (Note: I have re-calculated the total from the user's example to be accurate)

**Client's Game Idea/GDD:**
{{{gameIdea}}}

Now, based on the client's request, generate a detailed, itemized quote following the specified format and rules.
`,
});

const quoteGeneratorFlow = ai.defineFlow(
  {
    name: 'quoteGeneratorFlow',
    inputSchema: QuoteGeneratorInputSchema,
    outputSchema: QuoteGeneratorOutputSchema,
  },
  async (input) => {
    const {output} = await prompt(input);
    // Ensure totalCost is the sum of item costs
    const calculatedTotal = output?.items.reduce((sum, item) => sum + item.cost, 0) || 0;
    if (output) {
      output.totalCost = calculatedTotal;
    }
    return output!;
  }
);
