import {
  Code,
  Gamepad2,
  Brush,
  Check,
  Users,
  Briefcase,
  School,
  Download,
  Play,
  Video,
  Github,
  Linkedin,
  Wallet,
  Network,
  Cpu,
} from "lucide-react";
import { IconFiverr, IconUpwork, IconUnity, IconVisualStudio, IconFigma, IconPhotoshop, IconAdobeXD } from "@/components/icons";

export const navLinks = [
  { href: "#services", label: "Services" },
  { href: "#skills", label: "Skills" },
  { href: "#portfolio", label: "Portfolio" },
  { href: "#reviews", label: "Reviews" },
  { href: "#contact", label: "Contact" },
];

export const socialLinks = [
    { name: 'Fiverr', url: 'https://www.fiverr.com/users/shahrukhkhan9/', icon: IconFiverr },
    { name: 'Upwork', url: 'https://www.upwork.com/freelancers/~01d270e621d61cf22f', icon: IconUpwork },
    { name: 'GitHub', url: 'https://github.com', icon: Github },
    { name: 'LinkedIn', url: 'https://linkedin.com', icon: Linkedin },
];

export const about = {
    description: "I am a game developer with expertise in both Web3 (blockchain-integrated) and Web2 (traditional) game development, specializing in Unity to build immersive, high-quality games for PC, mobile, and web platforms. My skill set includes blockchain integration, NFT mechanics, wallet authentication, and cross-platform optimization, allowing me to develop innovative gaming experiences that seamlessly merge traditional and decentralized technologies.",
    email: "shahrukhyousafzaipk@gmail.com",
};

export const stats = [
    { value: "$128K+", label: "Total Earnings", icon: Check },
    { value: "166+", label: "Total Jobs", icon: Users },
    { value: "7+", label: "Years of Experience", icon: Briefcase },
];

export const timeline = [
    { date: "March 2017 - Jan 2023", title: "Senior Game Developer", description: "Efface Studios", icon: Briefcase },
    { date: "Jan 2017 - Present", title: "Freelancer", description: "Fiverr", icon: IconFiverr },
    { date: "April 2023 - July 2024", title: "Web3 Blockchain Unity Game Developer", description: "Efface Studios", icon: Cpu },
    { date: "2021 - 2025", title: "Bachelor of Business Administration (BBA)", description: "Islamia University of Bahawalpur", icon: School },
];

export const services = [
  { title: "Web2 & Traditional Game Development", icon: Gamepad2 },
  { title: "Web3 & Blockchain Game Integration", icon: Wallet },
  { title: "Cross-Platform Development", icon: Network },
  { title: "Game Systems & Mechanics", icon: Cpu },
];

export const skills = [
  { name: "Unity", icon: IconUnity },
  { name: "C#", icon: Code },
  { name: "Game Development", icon: Gamepad2 },
  { name: "Game Design", icon: Brush },
  { name: "Android App Development", icon: Cpu },
  { name: "iOS Development", icon: Cpu },
  { name: "Visual Studio", icon: IconVisualStudio },
  { name: "Figma", icon: IconFigma },
  { name: "Photoshop", icon: IconPhotoshop },
  { name: "Adobe XD", icon: IconAdobeXD },
];

export const languages = ["English", "Urdu", "Hindi", "Punjabi"];

export const projects = [
  {
    title: 'CrabGrab',
    description: 'An engaging 2D game focused on environmental cleanup. Players control a crab to grab litter and clean up the ocean.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'crab game',
    tags: ['Unity3D', '2D', 'Casual', 'Single Player', 'Simulation'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'The Pod',
    description: 'A social game where players can meet and interact with others, chat, make friends, and explore a vibrant world together.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'social game',
    tags: ['Unity3D', '3D', 'Multiplayer', 'Social', 'Simulation'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Panda Bear Mafia',
    description: 'A high-stakes casino blockchain game on the Solana chain. Players can stake $100 worth of SOL for a chance to win $1000.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'casino game',
    tags: ['Unity3D', 'Web3', 'Blockchain', 'Card Game', 'Multiplayer', 'Wallet'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'RugDollz World',
    description: 'An innovative mini-games library with Web2/Web3 compatibility, featuring a variety of game modes like PvP shooter, racing, and treasure hunting. Use NFTs to unlock exclusive content!',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'minigames world',
    tags: ['Unity3D', 'Web3', 'Multiplayer', 'Shooting', 'Racing', 'Action', 'RPG', 'Wallet'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Arcanes Edge',
    description: 'A Web3 blockchain survival game set in an endless, procedurally generated world. Features a building system that combines elements from Minecraft and Fortnite.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'survival game',
    tags: ['Unity3D', 'Web3', 'Blockchain', 'Survival', 'Open World', 'RPG', 'Action', 'Wallet'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'FutDice',
    description: 'A unique 2D sports game that blends the excitement of football with the strategy of dice rolls to control the action.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'football dice',
    tags: ['Unity3D', '2D', 'Sports', 'Board Game', 'Single Player', 'Multiplayer'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Many Cold Nights',
    description: 'A 3D open-world sandbox survival game set in a harsh, snowy environment. Players must build, thrive, and survive against the elements.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'snow survival',
    tags: ['Unity3D', '3D', 'Survival', 'Open World', 'Simulation'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Zord',
    description: 'An ambitious AAA quality game with mechanics and a vast world inspired by epic RPGs like Skyrim.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'fantasy rpg',
    tags: ['Unity3D', '3D', 'AAA', 'RPG', 'Open World', 'Action', 'Fighting'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Social Hub',
    description: 'A vibrant social game where you can meet new people, chat, make friends, and explore a dynamic world together.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'social game',
    tags: ['Unity3D', '3D', 'Multiplayer', 'Social', 'Simulation'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Shooting Arena 3D',
    description: 'A classic arcade-style shooting game where players can practice their aim on metal targets or take on waves of enemies, reminiscent of Virtua Cop.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'shooting range',
    tags: ['Unity3D', '3D', 'Shooting', 'Action', 'Single Player'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
    {
    title: 'Gear Head Racing',
    description: 'A 2D drag racing Web3 blockchain game with NFT integration for in-game assets, multiplayer functionality, and database implementation.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'drag racing',
    tags: ['Unity3D', 'Web3', 'Blockchain', 'Racing', '2D', 'Multiplayer', 'NFT', 'Wallet'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Solar Clicker: Click to Earn',
    description: 'A simple clicker game that increases the tap count and stores user taps in a leaderboard, with database implementation inspired by trending clicker crypto games.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'clicker game',
    tags: ['Unity3D', 'Web3', 'Blockchain', 'Clicker', 'Single Player'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Crypto Commando',
    description: 'Web3 Blockchain 3D Shooting game with a multiplayer battle royale mode and an offline single-player mode.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'soldier shooting',
    tags: ['Unity3D', 'Web3', 'Blockchain', 'Shooting', '3D', 'Multiplayer', 'Single Player', 'Action', 'Wallet'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Hall of Fame Racing',
    description: 'A Web3 goat racing game where users can choose from many types of goats, featuring database and multiplayer implementation.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'goat racing',
    tags: ['Unity3D', 'Web3', 'Blockchain', 'Racing', '3D', 'Multiplayer', 'Wallet'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'PlowedEarth',
    description: 'A web-based web3 blockchain, player-vs-player strategy game where you roll dice to move across a dynamic board, claim plots of land, and earn rent from other players.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'board game',
    tags: ['Unity3D', 'Web3', 'Blockchain', 'Board Game', 'Multiplayer', 'Strategy', 'Wallet'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'ToxicRipper',
    description: 'An endless runner game inspired by Subway Surfers where the character runs with a skateboard. It is also a web3 game with NFT implementation.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'skateboarding game',
    tags: ['Unity3D', 'Web3', 'Blockchain', 'Endless Runner', '3D', 'Single Player', 'Action', 'Wallet'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'RugDollz Shooter',
    description: 'A fast-paced PvP multiplayer shooter with four action-packed maps. Engage in intense battles where only the quickest and sharpest competitors come out on top.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'pvp shooter',
    tags: ['Unity3D', 'Web3', 'Multiplayer', 'Shooting', 'Action'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'RugDollz Racing',
    description: 'A high-speed multiplayer racing game featuring two exhilarating tracks, power-ups, and the ability to collect different kart NFTs for unique in-game vehicles.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'kart racing',
    tags: ['Unity3D', 'Web3', 'Multiplayer', 'Racing', 'NFT', 'Action'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'RugDollz Treasure',
    description: 'A unique PvP spin on capture the flag. Compete solo to secure treasure, defending it fiercely against rivals. Fight alongside powerful companions and upgrade your spell deck.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'treasure hunt',
    tags: ['Unity3D', 'Web3', 'Multiplayer', 'Action', 'Strategy'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'RugDollz Battle Royale',
    description: 'A thrilling battle royale minigame set in the RugDollz universe. Be the last one standing to claim victory.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'battle royale',
    tags: ['Unity3D', 'Web3', 'Multiplayer', 'Shooting', 'Action'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Crazy Punch',
    description: 'A hyper-casual brawler with wild ragdoll physics on floating islands. Knock opponents off to be the last one standing!',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'brawler game',
    tags: ['Unity3D', 'C#', 'Hyper-casual', 'Action', '3D', 'Single Player', 'Fighting'],
    link: 'https://drive.google.com/file/d/1Ww0gwXKG3slvU7sB3i2Gkdj87PdDxvER/view?usp=sharing',
    linkText: 'Download Now',
    linkIcon: Download,
    category: 'Games',
  },
  {
    title: 'Fall of Cars: Multiplayer',
    description: 'Maneuver your car to the correct color block before time runs out. Features real-time multiplayer battles.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'car game',
    tags: ['Unity3D', 'Multiplayer', 'Photon', '3D', 'Action', 'Racing'],
    link: 'https://www.dropbox.com/scl/fi/qi35thnupym0fhwir6sry/Fallofcars.apk?rlkey=upylas6l84xmoum8gkrbi74dy&dl=0',
    linkText: 'Download Now',
    linkIcon: Download,
    category: 'Games',
  },
  {
    title: 'Casino Clash - Multiplayer',
    description: 'A competitive multiplayer & offline card game where players aim to win by using cards of different colors and values.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'casino game',
    tags: ['Unity3D', 'Card Game', 'Multiplayer', '2D'],
    link: 'https://drive.google.com/file/d/1iWDQ_spIK8w3p53_94lfTg_A_n8WVmFs/view',
    linkText: 'Download Now',
    linkIcon: Download,
    category: 'Games',
  },
  {
    title: 'Basant Mela',
    description: 'Realistic Kite Flying and Fighting Simulator. Reached #4 trending in sports on Google Play with 500K+ downloads.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'kite game',
    tags: ['Unity3D', 'Mobile', 'Simulation', 'Sports', '3D', 'Single Player'],
    link: 'https://play.google.com/store/apps/details?id=com.EffaceStudios.BasantMela',
    linkText: 'Play Store',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Planet of Inus',
    description: 'An ambitious NFT Blockchain based MMORPG project. Built on MultiPlanetary INUS, which is the first-ever token to unify the top MEME Coin communities. This unique aspect of the game allows players to experience a truly decentralized gaming ecosystem where they can trade, buy, and sell in-game assets using NFTs.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'planet mmorpg',
    tags: ['Unity3D', 'Web3', 'Blockchain', 'MMORPG', 'AAA', 'NFT', 'Action', 'RPG', 'Wallet'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'World of Gods - MMORPG',
    description: 'A massively multiplayer online role-playing game with classes, guilds, crafting, and a huge world to explore.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'fantasy rpg',
    tags: ['Unity3D', 'MMORPG', 'Networking', 'Multiplayer', '3D', 'Action', 'RPG'],
    link: 'https://www.youtube.com/watch?v=ndsaZBDBJRw',
    linkText: 'Watch Video',
    linkIcon: Video,
    category: 'Games',
  },
  {
    title: 'Checkers Fall',
    description: 'A casual Checkers game with a unique twist - pieces fall with each move. Features multiplayer for endless fun.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'board game',
    tags: ['Unity3D', 'Board Game', 'Casual', 'Multiplayer', '2D', 'Sports'],
    link: 'https://www.crazygames.com/game/checkers-fall',
    linkText: 'Play Now',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Efface AI Chatbot Builder',
    description: 'Create a fully customized chatbot for your website in just a few clicks, completely offline.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'chatbot builder',
    tags: ['Windows', '.NET', 'AI'],
    link: 'https://youtu.be/RO68HhppuRg',
    linkText: 'Watch Video',
    linkIcon: Video,
    category: 'Apps',
  },
  {
    title: 'Flash - AI Presentation Maker',
    description: 'A revolutionary app that uses AI similar to GPT-4 to automate the creation of professional presentations.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'presentation maker',
    tags: ['Android', 'AI', 'Productivity'],
    link: 'https://play.google.com/store/apps/details?id=com.effacestudios.flashpresentationmaker',
    linkText: 'Download Now',
    linkIcon: Download,
    category: 'Apps',
  },
  {
    title: 'DocAdvisor - Your AI Doctor',
    description: 'Your trusted AI doctor, providing personalized and reliable treatment recommendations for a variety of symptoms.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'medical app',
    tags: ['Android', 'AI', 'Health'],
    link: 'https://play.google.com/store/apps/details?id=com.effacestudios.docadvisor',
    linkText: 'Download Now',
    linkIcon: Download,
    category: 'Apps',
  },
  {
    title: 'Instant - AI Video Maker',
    description: 'A next-level video creator that automates the process of searching, adding & finalizing video creation and editing.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'video editor',
    tags: ['Android', 'AI', 'Video Editing'],
    link: 'https://www.youtube.com/embed/bbBeo480n2M',
    linkText: 'Watch Video',
    linkIcon: Video,
    category: 'Apps',
  },
  {
    title: 'Planet of Inus - Cinematic',
    description: 'Cinematic trailer for an ambitious NFT Blockchain based MMORPG project.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'cinematic trailer',
    tags: ['Unity3D', 'Cinemachine', 'VFX'],
    link: 'https://www.youtube.com/watch?v=6qkWtXEh9b0',
    linkText: 'Watch on YouTube',
    linkIcon: Video,
    category: 'Animations',
  },
  {
    title: 'UFO.KO - Cinematic Trailer',
    description: 'Promotional cinematic trailer for the fun and competitive game UFO Knockout.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'game trailer',
    tags: ['Unity3D', 'Animation', 'Marketing'],
    link: 'https://www.youtube.com/watch?v=Vv1W0IwO42s',
    linkText: 'Watch on YouTube',
    linkIcon: Video,
    category: 'Animations',
  },
  {
    title: 'Short Animated Film',
    description: 'An example of a short animated story created using Unity for real-time rendering.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'animated short',
    tags: ['Unity3D', 'Storytelling', 'Real-time'],
    link: 'https://www.youtube.com/watch?v=vsW-VaQBH5k',
    linkText: 'Watch on YouTube',
    linkIcon: Video,
    category: 'Animations',
  },
];

export const testimonials = [
    {
        name: 'RugDollz World Game',
        title: 'Upwork Client',
        comment: "If you're looking for an amazing talented Game developer who is is efficient yet meticulous at game development, then choose Shah. He also has outstanding blockchain skills which is invaluable…",
        avatar: 'https://placehold.co/100x100.png',
        rating: 5,
    },
    {
        name: 'video + images + updates',
        title: 'Upwork Client',
        comment: "Been a joy working with him. Responds and works quickly and efficiently. Any updates I have he accomplishes them and does a great job",
        avatar: 'https://placehold.co/100x100.png',
        rating: 5,
    },
    {
        name: 'Battle royal Game',
        title: 'Upwork Client',
        comment: "Did a really great job! Done as requested and did updates asap as well, will continue working with him",
        avatar: 'https://placehold.co/100x100.png',
        rating: 5,
    },
    {
        name: 'Collisions map/objects + Interactions',
        title: 'Upwork Client',
        comment: "Shah have completed the job successfully as usual and he explained to me everything. The work was delivered on time.",
        avatar: 'https://placehold.co/100x100.png',
        rating: 5,
    },
    {
        name: '3D Monster hunt & Kingdom Defense',
        title: 'Upwork Client',
        comment: "It's been great working with you. Probably we can both do a little better in communication as we have done some things twice. Overall experience has been great.",
        avatar: 'https://placehold.co/100x100.png',
        rating: 4.7,
    }
];
