import {
  Code,
  Gamepad2,
  Brush,
  Check,
  Users,
  Briefcase,
  School,
  Download,
  Play,
  Video,
  Github,
  Linkedin,
  Wallet,
  Network,
  Cpu,
} from "lucide-react";
import { IconFiverr, IconUpwork, IconUnity, IconVisualStudio, IconFigma, IconPhotoshop, IconAdobeXD } from "@/components/icons";

export const navLinks = [
  { href: "#services", label: "Services" },
  { href: "#skills", label: "Skills" },
  { href: "#portfolio", label: "Portfolio" },
  { href: "#reviews", label: "Reviews" },
  { href: "#contact", label: "Contact" },
];

export const socialLinks = [
    { name: 'Fiverr', url: 'https://www.fiverr.com/users/shahrukhkhan9/', icon: IconFiverr },
    { name: 'Upwork', url: 'https://www.upwork.com/freelancers/~01d270e621d61cf22f', icon: IconUpwork },
    { name: 'GitHub', url: 'https://github.com', icon: Github },
    { name: 'LinkedIn', url: 'https://linkedin.com', icon: Linkedin },
];

export const about = {
    description: "I am a game developer with expertise in both Web3 (blockchain-integrated) and Web2 (traditional) game development, specializing in Unity to build immersive, high-quality games for PC, mobile, and web platforms. My skill set includes blockchain integration, NFT mechanics, wallet authentication, and cross-platform optimization, allowing me to develop innovative gaming experiences that seamlessly merge traditional and decentralized technologies.",
    email: "shahrukhyousafzaipk@gmail.com",
};

export const stats = [
    { value: "$128K+", label: "Total Earnings", icon: Check },
    { value: "166+", label: "Total Jobs", icon: Users },
    { value: "7+", label: "Years of Experience", icon: Briefcase },
];

export const timeline = [
    { date: "March 2017 - Jan 2023", title: "Senior Game Developer", description: "Efface Studios", icon: Briefcase },
    { date: "Jan 2017 - Present", title: "Freelancer", description: "Fiverr", icon: IconFiverr },
    { date: "April 2023 - July 2024", title: "Web3 Blockchain Unity Game Developer", description: "Efface Studios", icon: Cpu },
    { date: "2021 - 2025", title: "Bachelor of Business Administration (BBA)", description: "Islamia University of Bahawalpur", icon: School },
];

export const services = [
  { title: "Web2 & Traditional Game Development", icon: Gamepad2 },
  { title: "Web3 & Blockchain Game Integration", icon: Wallet },
  { title: "Cross-Platform Development", icon: Network },
  { title: "Game Systems & Mechanics", icon: Cpu },
];

export const skills = [
  { name: "Unity", icon: IconUnity },
  { name: "C#", icon: Code },
  { name: "Game Development", icon: Gamepad2 },
  { name: "Game Design", icon: Brush },
  { name: "Android App Development", icon: Cpu },
  { name: "iOS Development", icon: Cpu },
  { name: "Visual Studio", icon: IconVisualStudio },
  { name: "Figma", icon: IconFigma },
  { name: "Photoshop", icon: IconPhotoshop },
  { name: "Adobe XD", icon: IconAdobeXD },
];

export const languages = ["English", "Urdu", "Hindi", "Punjabi"];

export const projects = [
  {
    title: 'CrabGrab',
    description: 'An engaging 2D game focused on environmental cleanup. Players control a crab to grab litter and clean up the ocean.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'crab game',
    tags: ['Unity3D', '2D', 'Casual', 'Single Player', 'Simulation'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'The Pod',
    description: 'A social game where players can meet and interact with others, chat, make friends, and explore a vibrant world together.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'social game',
    tags: ['Unity3D', '3D', 'Multiplayer', 'Social', 'Simulation'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Panda Bear Mafia',
    description: 'A high-stakes casino blockchain game on the Solana chain. Players can stake $100 worth of SOL for a chance to win $1000.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'casino game',
    tags: ['Unity3D', 'Web3', 'Blockchain', 'Card Game', 'Casino', 'Multiplayer', 'Wallet'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'RugDollz World',
    description: 'An innovative mini-games library with Web2/Web3 compatibility, featuring a variety of game modes like PvP shooter, racing, and treasure hunting. Use NFTs to unlock exclusive content!',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'minigames world',
    tags: ['Unity3D', 'Web3', 'Multiplayer', 'Shooting', 'Racing', 'Action', 'RPG', 'Wallet'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Arcanes Edge',
    description: 'A Web3 blockchain survival game set in an endless, procedurally generated world. Features a building system that combines elements from Minecraft and Fortnite.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'survival game',
    tags: ['Unity3D', 'Web3', 'Blockchain', 'Survival', 'Open World', 'RPG', 'Action', 'Wallet'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'FutDice',
    description: 'A unique 2D sports game that blends the excitement of football with the strategy of dice rolls to control the action.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'football dice',
    tags: ['Unity3D', '2D', 'Sports', 'Board Game', 'Single Player', 'Multiplayer'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Many Cold Nights',
    description: 'A 3D open-world sandbox survival game set in a harsh, snowy environment. Players must build, thrive, and survive against the elements.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'snow survival',
    tags: ['Unity3D', '3D', 'Survival', 'Open World', 'Simulation'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Zord RPG',
    description: 'An ambitious AAA quality game with mechanics and a vast world inspired by epic RPGs like Skyrim.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'fantasy rpg',
    tags: ['Unity3D', '3D', 'AAA', 'RPG', 'Open World', 'Action', 'Fighting'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Social Hub',
    description: 'A vibrant social game where you can meet new people, chat, make friends, and explore a dynamic world together.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'social game',
    tags: ['Unity3D', '3D', 'Multiplayer', 'Social', 'Simulation'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Shooting Arena 3D',
    description: 'A classic arcade-style shooting game where players can practice their aim on metal targets or take on waves of enemies, reminiscent of Virtua Cop.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'shooting range',
    tags: ['Unity3D', '3D', 'Shooting', 'Action', 'Single Player'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Gear Head Racing',
    description: 'A 2D drag racing Web3 blockchain game with NFT integration for in-game assets, multiplayer functionality, and database implementation.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'drag racing',
    tags: ['Unity3D', 'Web3', 'Blockchain', 'Racing', '2D', 'Multiplayer', 'NFT', 'Wallet'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Solar Clicker: Click to Earn',
    description: 'A simple clicker game that increases the tap count and stores user taps in a leaderboard, with database implementation inspired by trending clicker crypto games.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'clicker game',
    tags: ['Unity3D', 'Web3', 'Blockchain', 'Clicker', 'Single Player'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Crypto Commando',
    description: 'Web3 Blockchain 3D Shooting game with a multiplayer battle royale mode and an offline single-player mode.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'soldier shooting',
    tags: ['Unity3D', 'Web3', 'Blockchain', 'Shooting', '3D', 'Multiplayer', 'Single Player', 'Action', 'Wallet', 'Battle Royale'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Hall of Fame Racing',
    description: 'A Web3 goat racing game where users can choose from many types of goats, featuring database and multiplayer implementation.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'goat racing',
    tags: ['Unity3D', 'Web3', 'Blockchain', 'Racing', '3D', 'Multiplayer', 'Wallet'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'PlowedEarth',
    description: 'A web-based web3 blockchain, player-vs-player strategy game where you roll dice to move across a dynamic board, claim plots of land, and earn rent from other players.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'board game',
    tags: ['Unity3D', 'Web3', 'Blockchain', 'Board Game', 'Multiplayer', 'Strategy', 'Wallet'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'ToxicRipper',
    description: 'An endless runner game inspired by Subway Surfers where the character runs with a skateboard. It is also a web3 game with NFT implementation.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'skateboarding game',
    tags: ['Unity3D', 'Web3', 'Blockchain', 'Endless Runner', '3D', 'Single Player', 'Action', 'Wallet'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'RugDollz Shooter',
    description: 'A fast-paced PvP multiplayer shooter with four action-packed maps. Engage in intense battles where only the quickest and sharpest competitors come out on top.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'pvp shooter',
    tags: ['Unity3D', 'Web3', 'Multiplayer', 'Shooting', 'Action'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'RugDollz Racing',
    description: 'A high-speed multiplayer racing game featuring two exhilarating tracks, power-ups, and the ability to collect different kart NFTs for unique in-game vehicles.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'kart racing',
    tags: ['Unity3D', 'Web3', 'Multiplayer', 'Racing', 'NFT', 'Action'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'RugDollz Treasure',
    description: 'A unique PvP spin on capture the flag. Compete solo to secure treasure, defending it fiercely against rivals. Fight alongside powerful companions and upgrade your spell deck.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'treasure hunt',
    tags: ['Unity3D', 'Web3', 'Multiplayer', 'Action', 'Strategy'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'RugDollz Battle Royale',
    description: 'A thrilling battle royale minigame set in the RugDollz universe. Be the last one standing to claim victory.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'battle royale',
    tags: ['Unity3D', 'Web3', 'Multiplayer', 'Shooting', 'Action', 'Battle Royale'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Crazy Punch',
    description: 'A hyper-casual brawler with wild ragdoll physics on floating islands. Knock opponents off to be the last one standing!',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'brawler game',
    tags: ['Unity3D', 'C#', 'Hyper-casual', 'Action', '3D', 'Single Player', 'Fighting'],
    link: 'https://drive.google.com/file/d/1Ww0gwXKG3slvU7sB3i2Gkdj87PdDxvER/view?usp=sharing',
    linkText: 'Download Now',
    linkIcon: Download,
    category: 'Games',
  },
  {
    title: 'Fall of Cars: Multiplayer',
    description: 'Maneuver your car to the correct color block before time runs out. Features real-time multiplayer battles.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'car game',
    tags: ['Unity3D', 'Multiplayer', 'Photon', '3D', 'Action', 'Racing'],
    link: 'https://www.dropbox.com/scl/fi/qi35thnupym0fhwir6sry/Fallofcars.apk?rlkey=upylas6l84xmoum8gkrbi74dy&dl=0',
    linkText: 'Download Now',
    linkIcon: Download,
    category: 'Games',
  },
  {
    title: 'Basant Mela',
    description: 'Realistic Kite Flying and Fighting Simulator. Reached #4 trending in sports on Google Play with 500K+ downloads.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'kite game',
    tags: ['Unity3D', 'Mobile', 'Simulation', 'Sports', '3D', 'Single Player'],
    link: 'https://play.google.com/store/apps/details?id=com.EffaceStudios.BasantMela',
    linkText: 'Play Store',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Planet of Inus',
    description: 'An ambitious NFT Blockchain based MMORPG project. Built on MultiPlanetary INUS, which is the first-ever token to unify the top MEME Coin communities. This unique aspect of the game allows players to experience a truly decentralized gaming ecosystem where they can trade, buy, and sell in-game assets using NFTs.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'planet mmorpg',
    tags: ['Unity3D', 'Web3', 'Blockchain', 'MMORPG', 'AAA', 'NFT', 'Action', 'RPG', 'Wallet'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Solar Dominion',
    description: 'Sentries versus Serpents in this multiplayer shooting adventure. Team up or compete to earn rewards. The only shooting game that rewards players prizes weekly. Actively work your way up the ranks and earn prizes!',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'multiplayer shooter',
    tags: ['Unity3D', 'Web3', 'Shooting', 'Action', 'Multiplayer', 'Battle Royale', 'NFT', 'Wallet', 'Competitive'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'World of Gods - MMORPG',
    description: 'A massively multiplayer online role-playing game with classes, guilds, crafting, and a huge world to explore.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'fantasy rpg',
    tags: ['Unity3D', 'MMORPG', 'Networking', 'Multiplayer', '3D', 'Action', 'RPG'],
    link: 'https://www.youtube.com/watch?v=ndsaZBDBJRw',
    linkText: 'Watch Video',
    linkIcon: Video,
    category: 'Games',
  },
  {
    title: 'Checkers Fall',
    description: 'A casual Checkers game with a unique twist - pieces fall with each move. Features multiplayer for endless fun.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'board game',
    tags: ['Unity3D', 'Board Game', 'Casual', 'Multiplayer', '2D', 'Sports'],
    link: 'https://www.crazygames.com/game/checkers-fall',
    linkText: 'Play Now',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Merge Turret: Monster Defense',
    description: 'An exhilarating blend of defense and merge gameplay! Defend your fortress by strategically merging and upgrading powerful turrets to combat waves of relentless monsters.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'tower defense',
    tags: ['Unity3D', 'Defense', 'Merge', 'Single Player', 'Strategy'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'QuizGenius',
    description: 'A cutting-edge mobile app with AI-powered functionality that generates unlimited quizzes to stimulate your cognitive abilities and enhance your mental agility.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'quiz app',
    tags: ['Unity3D', 'AI', 'Quiz', 'Mobile', 'Single Player', 'ChatGPT'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Color Clash - Multiplayer Card Game',
    description: 'A competitive multiplayer & offline card game where players aim to win by using cards of different colors and values. Features special cards to counter opponents and strategic round-based gameplay.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'card game',
    tags: ['Unity3D', 'Card Game', 'Casino', 'Multiplayer', '2D'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Casino Bomb - Multiplayer Game',
    description: 'A competitive multiplayer & offline card game where players aim to win by getting rid of all pairs of identical cards in hand to win while using elimination cards to eliminate other players. Includes an avatar system and matchmaking.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'casino game',
    tags: ['Unity3D', 'Card Game', 'Casino', 'Multiplayer', 'Photon'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Boosted!™ - An Original Card Game',
    description: 'An original card game where players use skill, tactics, and special Booster Cards to be the first to get rid of all their playing cards. Features unique mechanics like calling "higher" or "lower" to outwit opponents.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'card game',
    tags: ['Unity3D', 'Card Game', 'Casino', 'Multiplayer', 'Strategy'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'UFO.KO - Multiplayer UFO Game',
    description: 'A super fun UFO beam it all up arena map game. Fly a round as a cool UFO and beam up as much as you can to grow in size which will allow you to get bigger items, even beam up other players! Explore four worlds that are city, desert, temple, and ice themed.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'ufo game',
    tags: ['Unity3D', 'Multiplayer', 'Action', '3D', 'Arena'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Traffic Loop - Car Racing Mobile Game',
    description: 'Car race game you can drive to feel the racing car speed and enjoy the real car racing games experience. If you have a thrill of car racing and you are handy at car driving games, try this traffic racing car game and dive into the fun of new car games.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'car racing',
    tags: ['Unity3D', 'Racing', 'Mobile', 'Single Player'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Super Style Volley - SSV',
    description: 'Super Style Volley is a 2D volleyball game that features fast-paced and action-packed gameplay. Players can choose from a variety of cards, each with their own unique abilities and attributes. The game features multiple game modes, including single player, local multiplayer, and online multiplayer.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'volleyball game',
    tags: ['Unity3D', 'Sports', '2D', 'Multiplayer', 'Single Player', 'Action'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Football Tactics',
    description: 'FootBall Tactics is an innovative multiplayer tactical sports game that combines the strategic gameplay of turn-based games like Fire Emblem with the competitive spirit of online sports games such as FIFA. The game is played on a football field where players will compete against each other by placing their characters on the field and issuing orders for the next turn.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'football tactics',
    tags: ['Unity3D', 'Sports', 'Strategy', 'Multiplayer', 'Turn-based'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Restaurant Game Prototype',
    description: 'In this fast-paced and addictive game, you take on the role of a coffee shop owner, tasked with serving up delicious drinks and snacks to a steady stream of customers. The gameplay loop is simple but challenging, as you race against the clock to fulfill each order and keep your customers happy.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'restaurant game',
    tags: ['Unity3D', 'Simulation', 'Single Player', 'Casual'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Element Royale',
    description: 'Welcome to Element Royale, the ultimate battle game where players must conquer their opponents using the power of the elements! Engage in intense player versus player combat, break through enemy defenses and earn more trophies as you progress through the ranks.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'battle game',
    tags: ['Unity3D', 'Battle Royale', 'Action', 'Multiplayer', 'Co-op'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Letter Crush: Fun Crossword',
    description: 'Letter Crush: Fun Crossword Game. Play it for at least 10 minutes a day, and it will help you stay sharp and prepared for everyday challenges! This daily themed crossword puzzle text twist game is tremendously brain challenging and fun to play.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'word puzzle',
    tags: ['Unity3D', 'Puzzle', 'Word Game', 'Single Player', 'Casual'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Games',
  },
  {
    title: 'Multi-Avatar AI 3D Chatbot',
    description: 'Discover the future of interactive communication with our AI 3D Chatbot, featuring a diverse range of customizable avatars to suit your style! This cutting-edge chatbot offers Wikipedia integration, providing you instant access to a wealth of knowledge at your fingertips. With advanced Text-to-Speech (TTS) capabilities, the chatbot can read information aloud, enhancing your learning experience. Its voice recognition technology allows for natural, hands-free interactions, while powerful translation features enable seamless communication in any language.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'ai chatbot',
    tags: ['AI', '3D', 'Chatbot', 'TTS', 'Voice Recognition', 'Wikipedia', 'Translation'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Apps',
  },
  {
    title: 'Interactive AI Chatbot App',
    description: 'This innovative app allows the chatbot to remember your name and high scores, making each session personalized and engaging. The chatbot can listen and understand your preferences—tell it your favorite color, and watch as the game sphere changes to match your choice! You can interact with the friendly 3D chatbot through voice commands using your microphone or by typing via the keyboard, creating a dynamic conversation that enhances gameplay.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'interactive chatbot',
    tags: ['AI', 'Chatbot', 'Personalization', 'Voice Recognition', 'Mobile'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Apps',
  },
  {
    title: 'Efface AI Chatbot',
    description: 'This AI chatbot features voice-to-text speech recognition for seamless, hands-free conversations and voice response capabilities for natural interaction. It includes automated email notifications for updates and confirmations, ensuring users stay informed. The chatbot supports custom branding with personalized logos and a variety of color options to match your business identity. Additionally, it offers customizable contact or link buttons for easy navigation and quick access. Designed for an engaging, branded user experience.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'business chatbot',
    tags: ['AI', 'Chatbot', 'Voice Recognition', 'Branding', 'Email'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Apps',
  },
  {
    title: 'AI Chatbots With Avatar',
    description: 'An interactive, multi-modal AI chatbot featuring advanced voice-to-text, voice response, a visually engaging 3D avatar, email notifications, and custom branding.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'avatar chatbot',
    tags: ['AI', 'Chatbot', '3D Avatar', 'Voice Recognition'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Apps',
  },
  {
    title: 'AI Image Generator',
    description: 'A web app that creates custom images from text prompts using AI. Features an intuitive UI with React.js and Tailwind CSS, perfect for artists and designers.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'image generation',
    tags: ['AI', 'React.js', 'Web App', 'Productivity'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Apps',
  },
  {
    title: 'QuickChef - AI Recipe Guide',
    description: 'The ultimate cooking companion that transforms your available ingredients into delicious recipes using AI. Features a vast, ever-expanding library for all dietary needs.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'recipe app',
    tags: ['AI', 'Mobile App', 'Productivity', 'Food', 'Unity3D', 'ChatGPT'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Apps',
  },
  {
    title: 'DateShate - Random Chat & Date',
    description: 'A social media mobile app to meet and chat with random people worldwide. Features voice chat, custom avatars, and a clever AI chatbot fallback for when no users are available.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'dating app',
    tags: ['Social', 'Mobile App', 'Chat', 'AI Chatbot', 'Dating'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Apps',
  },
  {
    title: 'Efface Character Creator',
    description: 'Create and customize game characters in no time. Export them as 2D sprites for use in game engines like Unity, Unreal Engine, and Construct 2.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'character creator',
    tags: ['Windows', 'Productivity', 'Game Development', '2D'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Apps',
  },
  {
    title: 'WP Chatbot Builder',
    description: 'A WordPress plugin that allows you to build and manage multiple chatbots for your websites with full customization and a live preview system.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'wordpress plugin',
    tags: ['WordPress', 'Chatbot', 'AI', 'Web'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Apps',
  },
  {
    title: 'Spectruma - Audio Visualizer Maker',
    description: 'A lightweight mobile application for musicians, artists, and podcasters to create professional audio spectrum visualizers for their tracks and podcasts.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'audio visualizer',
    tags: ['Mobile App', 'Music', 'Productivity', 'Video'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Apps',
  },
  {
    title: 'Efface Auto Typing Bot',
    description: 'A handy bot that automates typing for you. Enter your text, set a delay, and let the bot type it out in any application, saving you time from repetitive copy-pasting.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'typing bot',
    tags: ['Windows', 'Productivity', 'Automation'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Apps',
  },
  {
    title: 'Efface Text Story Maker',
    description: 'A simple Windows application that lets you write text message-style stories and export them as videos to share with friends. Features full customization of the chat interface.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'story maker',
    tags: ['Windows', 'Video', 'Creative', 'Social'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Apps',
  },
  {
    title: 'Efface AI Chatbot Builder',
    description: 'Create AI Chatbots for your website offline with this Windows application. Features full customization and multiple export options, including Web App, WordPress Plugin, and Windows Application.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'chatbot builder',
    tags: ['Windows', 'AI', 'Chatbot', 'Productivity', 'Offline'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Apps',
  },
  {
    title: 'PDF Flipbook Builder',
    description: 'A Windows application to convert any PDF file into a responsive, interactive flipbook. Works offline and offers extensive customization for a professional look.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'pdf flipbook',
    tags: ['Windows', 'Productivity', 'PDF', 'Offline'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Apps',
  },
  {
    title: 'AnimStorm 2.0 Chatbot & Spokesperson',
    description: 'A dual-mode Windows application to create animated spokesperson videos or an AI chatbot using AIML. Features 720p HD recording and character customization.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'animated spokesperson',
    tags: ['Windows', 'Animation', 'AI', 'Chatbot', 'Video'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Apps',
  },
  {
    title: 'AnimStorm Studio',
    description: 'A highly customizable animation software for creating spokesperson videos. Features funny skins, various emotions, and more to bring your characters to life.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'animation studio',
    tags: ['Windows', 'Animation', 'Creative', 'Video'],
    link: '#',
    linkText: 'Learn More',
    linkIcon: Play,
    category: 'Apps',
  },
  {
    title: 'Planet of Inus - Cinematic',
    description: 'Cinematic trailer for an ambitious NFT Blockchain based MMORPG project.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'cinematic trailer',
    tags: ['Unity3D', 'Cinemachine', 'VFX'],
    link: 'https://www.youtube.com/watch?v=6qkWtXEh9b0',
    linkText: 'Watch on YouTube',
    linkIcon: Video,
    category: 'Animations',
  },
  {
    title: 'UFO.KO - Cinematic Trailer',
    description: 'Promotional cinematic trailer for the fun and competitive game UFO Knockout.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'game trailer',
    tags: ['Unity3D', 'Animation', 'Marketing'],
    link: 'https://www.youtube.com/watch?v=Vv1W0IwO42s',
    linkText: 'Watch on YouTube',
    linkIcon: Video,
    category: 'Animations',
  },
  {
    title: 'Short Animated Film',
    description: 'An example of a short animated story created using Unity for real-time rendering.',
    image: 'https://placehold.co/600x400.png',
    aiHint: 'animated short',
    tags: ['Unity3D', 'Storytelling', 'Real-time'],
    link: 'https://www.youtube.com/watch?v=vsW-VaQBH5k',
    linkText: 'Watch on YouTube',
    linkIcon: Video,
    category: 'Animations',
  },
];

export const testimonials = [
    {
        name: 'RugDollz World Game',
        title: 'Upwork Client',
        comment: "If you're looking for an amazing talented Game developer who is is efficient yet meticulous at game development, then choose Shah. He also has outstanding blockchain skills which is invaluable…",
        avatar: 'https://placehold.co/100x100.png',
        rating: 5,
    },
    {
        name: 'video + images + updates',
        title: 'Upwork Client',
        comment: "Been a joy working with him. Responds and works quickly and efficiently. Any updates I have he accomplishes them and does a great job",
        avatar: 'https://placehold.co/100x100.png',
        rating: 5,
    },
    {
        name: 'Battle royal Game',
        title: 'Upwork Client',
        comment: "Did a really great job! Done as requested and did updates asap as well, will continue working with him",
        avatar: 'https://placehold.co/100x100.png',
        rating: 5,
    },
    {
        name: 'Collisions map/objects + Interactions',
        title: 'Upwork Client',
        comment: "Shah have completed the job successfully as usual and he explained to me everything. The work was delivered on time.",
        avatar: 'https://placehold.co/100x100.png',
        rating: 5,
    },
    {
        name: '3D Monster hunt & Kingdom Defense',
        title: 'Upwork Client',
        comment: "It's been great working with you. Probably we can both do a little better in communication as we have done some things twice. Overall experience has been great.",
        avatar: 'https://placehold.co/100x100.png',
        rating: 4.7,
    }
];
