'use server';

import asBlob from 'html-to-docx';

export async function generateDocx(htmlString: string, title: string) {
  try {
    const footer = `
      <br /><br />
      <p style="text-align:center;font-size:10px;color:grey;">
        <em>
          This document was generated by an AI tool from the Shahrukh Yousafzai Portfolio. The content herein is an estimate and is intended for preliminary planning purposes.
        </em>
      </p>
    `;

    const fullHtml = `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <title>${title}</title>
      </head>
      <body>
        ${htmlString}
        ${footer}
      </body>
      </html>
    `;

    const fileBuffer = await asBlob(fullHtml, {
      orientation: 'portrait',
      margins: { top: 720, right: 720, bottom: 720, left: 720 },
    });

    if (Buffer.isBuffer(fileBuffer)) {
        return fileBuffer.toString('base64');
    }
    
    const buffer = Buffer.from(await (fileBuffer as Blob).arrayBuffer());
    return buffer.toString('base64');
  } catch (error) {
    console.error('Error generating DOCX:', error);
    throw new Error('Failed to generate DOCX file.');
  }
}
